/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.interfaces;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import py.edu.fiuni.clientes.Cliente;
import py.edu.fiuni.expections.IsEmptyException;
import py.edu.fiuni.gestores.GestorClientes;
import py.edu.fiuni.gestores.GestorPeliculas;
import py.edu.fiuni.peliculas.Pelicula;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    DefaultTableModel modelPeliculas;
    DefaultTableModel modelClientes;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        pnlInicio_pnl.setVisible(true);
        pnlInventario_pnl.setVisible(false);
        pnlClientes_pnl.setVisible(false);
        pnlCaja_pnl.setVisible(false);

        //Marcamos casilla como seleccionada
        btnInicio_pnl.setBackground(new java.awt.Color(130, 38, 104));
        btnInventario_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnClientes_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnCaja_pnl.setBackground(new java.awt.Color(144, 12, 62));
        
        modelPeliculas = (DefaultTableModel) tblaPeliculas_tble.getModel();
        modelClientes = (DefaultTableModel) tblaClientes_tble.getModel();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btnInicio_pnl = new javax.swing.JPanel();
        iconInicio_label = new javax.swing.JLabel();
        textInicio_label = new javax.swing.JLabel();
        btnInventario_pnl = new javax.swing.JPanel();
        iconInventario_label = new javax.swing.JLabel();
        textInventario_label = new javax.swing.JLabel();
        btnClientes_pnl = new javax.swing.JPanel();
        iconClientes_label = new javax.swing.JLabel();
        textClientes_label = new javax.swing.JLabel();
        btnCaja_pnl = new javax.swing.JPanel();
        iconCaja_label = new javax.swing.JLabel();
        textCaja_label = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        pnlInicio_pnl = new javax.swing.JPanel();
        lblInicio_lbl = new javax.swing.JLabel();
        lblExplicacionProgram = new javax.swing.JLabel();
        lblExplicacionProgram1 = new javax.swing.JLabel();
        lblExplicacionProgram2 = new javax.swing.JLabel();
        lblExplicacionProgram3 = new javax.swing.JLabel();
        lblExplicacionProgram4 = new javax.swing.JLabel();
        lblExplicacionPoliticas = new javax.swing.JLabel();
        lblExplicacionPoliticas1 = new javax.swing.JLabel();
        lblExplicacionPoliticas2 = new javax.swing.JLabel();
        pnlInventario_pnl = new javax.swing.JPanel();
        btnAddPelicula_btn = new javax.swing.JButton();
        btnBuscarPelicula_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblaPeliculas_tble = new javax.swing.JTable();
        pnlClientes_pnl = new javax.swing.JPanel();
        btnAddCliente_btn = new javax.swing.JButton();
        btnBuscarBorrar_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblaClientes_tble = new javax.swing.JTable();
        pnlCaja_pnl = new javax.swing.JPanel();
        textFecha_field = new javax.swing.JTextField();
        textFecha_lbl = new javax.swing.JLabel();
        btnNuevaOperacionDeAlquiler_btn = new javax.swing.JButton();
        btnDevolverPelicula_btn = new javax.swing.JButton();
        btnRefresh_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(87, 24, 69));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnInicio_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicio_pnlMouseClicked(evt);
            }
        });
        btnInicio_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconInicio_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/edu/fiuni/imagenes/casax32.png"))); // NOI18N
        btnInicio_pnl.add(iconInicio_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        textInicio_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textInicio_label.setForeground(new java.awt.Color(255, 255, 255));
        textInicio_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textInicio_label.setText("Inicio");
        btnInicio_pnl.add(textInicio_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 30));

        sidePanel.add(btnInicio_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 50));

        btnInventario_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnInventario_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventario_pnlMouseClicked(evt);
            }
        });
        btnInventario_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconInventario_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/edu/fiuni/imagenes/inventariox32.png"))); // NOI18N
        btnInventario_pnl.add(iconInventario_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        textInventario_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textInventario_label.setForeground(new java.awt.Color(255, 255, 255));
        textInventario_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textInventario_label.setText("Inventario");
        btnInventario_pnl.add(textInventario_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, 30));

        sidePanel.add(btnInventario_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 190, 50));

        btnClientes_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnClientes_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientes_pnlMouseClicked(evt);
            }
        });
        btnClientes_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconClientes_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/edu/fiuni/imagenes/userx32.png"))); // NOI18N
        btnClientes_pnl.add(iconClientes_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        textClientes_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textClientes_label.setForeground(new java.awt.Color(255, 255, 255));
        textClientes_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textClientes_label.setText("Clientes");
        btnClientes_pnl.add(textClientes_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 30));

        sidePanel.add(btnClientes_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, 50));

        btnCaja_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnCaja_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCaja_pnlMouseClicked(evt);
            }
        });
        btnCaja_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconCaja_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/edu/fiuni/imagenes/shopping-cart.png"))); // NOI18N
        btnCaja_pnl.add(iconCaja_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        textCaja_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textCaja_label.setForeground(new java.awt.Color(255, 255, 255));
        textCaja_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textCaja_label.setText("Caja");
        btnCaja_pnl.add(textCaja_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 30));

        sidePanel.add(btnCaja_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 50));

        background.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        topPanel.setBackground(new java.awt.Color(87, 24, 69));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 610, 50));

        lblInicio_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInicio_lbl.setText("Inicio");

        lblExplicacionProgram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionProgram.setText("Porgrama para DVDStore, lo que realiza este programa es:");

        lblExplicacionProgram1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionProgram1.setText("*Gestionar los clientes.");

        lblExplicacionProgram2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionProgram2.setText("*Gestionar los alquileres de DVDs.");

        lblExplicacionProgram3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionProgram3.setText("*Gestioinar devoluciones de DVDs.");

        lblExplicacionProgram4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionProgram4.setText("*Realiza los calculos de multa por atraso de entrega.");

        lblExplicacionPoliticas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionPoliticas.setText("Las politicas son:");

        lblExplicacionPoliticas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionPoliticas1.setText("*Cada pelicula se alquila por una semana.");

        lblExplicacionPoliticas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicacionPoliticas2.setText("*Cada dia de retraso al entregar la pelicula se le agrega una multa de 5$.");

        javax.swing.GroupLayout pnlInicio_pnlLayout = new javax.swing.GroupLayout(pnlInicio_pnl);
        pnlInicio_pnl.setLayout(pnlInicio_pnlLayout);
        pnlInicio_pnlLayout.setHorizontalGroup(
            pnlInicio_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicio_pnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlInicio_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInicio_lbl)
                    .addComponent(lblExplicacionProgram)
                    .addComponent(lblExplicacionProgram1)))
            .addGroup(pnlInicio_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExplicacionProgram2))
            .addGroup(pnlInicio_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExplicacionProgram3))
            .addGroup(pnlInicio_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExplicacionProgram4))
            .addGroup(pnlInicio_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInicio_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExplicacionPoliticas)
                    .addComponent(lblExplicacionPoliticas1)
                    .addComponent(lblExplicacionPoliticas2)))
        );
        pnlInicio_pnlLayout.setVerticalGroup(
            pnlInicio_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicio_pnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblInicio_lbl)
                .addGap(20, 20, 20)
                .addComponent(lblExplicacionProgram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExplicacionProgram1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExplicacionProgram2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExplicacionProgram3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExplicacionProgram4)
                .addGap(18, 18, 18)
                .addComponent(lblExplicacionPoliticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExplicacionPoliticas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExplicacionPoliticas2)
                .addGap(276, 276, 276))
        );

        background.add(pnlInicio_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 610, 550));

        btnAddPelicula_btn.setText("Agregar Película");
        btnAddPelicula_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPelicula_btnActionPerformed(evt);
            }
        });

        btnBuscarPelicula_btn.setText("Buscar Película");
        btnBuscarPelicula_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPelicula_btnActionPerformed(evt);
            }
        });

        tblaPeliculas_tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Genero", "Año", "Reseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblaPeliculas_tble);

        javax.swing.GroupLayout pnlInventario_pnlLayout = new javax.swing.GroupLayout(pnlInventario_pnl);
        pnlInventario_pnl.setLayout(pnlInventario_pnlLayout);
        pnlInventario_pnlLayout.setHorizontalGroup(
            pnlInventario_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventario_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventario_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(pnlInventario_pnlLayout.createSequentialGroup()
                        .addComponent(btnAddPelicula_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarPelicula_btn)))
                .addContainerGap())
        );
        pnlInventario_pnlLayout.setVerticalGroup(
            pnlInventario_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventario_pnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlInventario_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPelicula_btn)
                    .addComponent(btnAddPelicula_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(pnlInventario_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 600, 550));

        btnAddCliente_btn.setText("Agregar Cliente");
        btnAddCliente_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCliente_btnActionPerformed(evt);
            }
        });

        btnBuscarBorrar_btn.setText("Borrar Cliente");
        btnBuscarBorrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBorrar_btnActionPerformed(evt);
            }
        });

        tblaClientes_tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "CI", "Deuda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblaClientes_tble);

        javax.swing.GroupLayout pnlClientes_pnlLayout = new javax.swing.GroupLayout(pnlClientes_pnl);
        pnlClientes_pnl.setLayout(pnlClientes_pnlLayout);
        pnlClientes_pnlLayout.setHorizontalGroup(
            pnlClientes_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientes_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientes_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(pnlClientes_pnlLayout.createSequentialGroup()
                        .addComponent(btnAddCliente_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarBorrar_btn)))
                .addContainerGap())
        );
        pnlClientes_pnlLayout.setVerticalGroup(
            pnlClientes_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientes_pnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlClientes_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarBorrar_btn)
                    .addComponent(btnAddCliente_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(pnlClientes_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 600, 550));

        textFecha_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFecha_fieldActionPerformed(evt);
            }
        });

        textFecha_lbl.setText("Fecha:");

        btnNuevaOperacionDeAlquiler_btn.setText("Nuevo Alquiler");

        btnDevolverPelicula_btn.setText("Devolver Película");

        btnRefresh_btn.setText("Actualizar Tabla");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Cliente", "Pelicula Alquilada", "Monto Pagado", "Deuda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout pnlCaja_pnlLayout = new javax.swing.GroupLayout(pnlCaja_pnl);
        pnlCaja_pnl.setLayout(pnlCaja_pnlLayout);
        pnlCaja_pnlLayout.setHorizontalGroup(
            pnlCaja_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaja_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCaja_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(pnlCaja_pnlLayout.createSequentialGroup()
                        .addComponent(btnNuevaOperacionDeAlquiler_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDevolverPelicula_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFecha_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFecha_field, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCaja_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefresh_btn)))
                .addContainerGap())
        );
        pnlCaja_pnlLayout.setVerticalGroup(
            pnlCaja_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaja_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCaja_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFecha_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFecha_lbl)
                    .addComponent(btnNuevaOperacionDeAlquiler_btn)
                    .addComponent(btnDevolverPelicula_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh_btn)
                .addContainerGap())
        );

        background.add(pnlCaja_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 600, 550));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicio_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicio_pnlMouseClicked
        // TODO add your handling code here:
        apretarBotonInicio();
    }//GEN-LAST:event_btnInicio_pnlMouseClicked

    private void btnInventario_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventario_pnlMouseClicked
        // TODO add your handling code here:
        apretarBotonInventario();
    }//GEN-LAST:event_btnInventario_pnlMouseClicked

    private void btnClientes_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientes_pnlMouseClicked
        // TODO add your handling code here:
        apretarBotonClientes();
    }//GEN-LAST:event_btnClientes_pnlMouseClicked

    private void btnCaja_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaja_pnlMouseClicked
        // TODO add your handling code here:
        apretarBotonCaja();
    }//GEN-LAST:event_btnCaja_pnlMouseClicked

    private void btnAddPelicula_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPelicula_btnActionPerformed
        // TODO add your handling code here:
        addPelicula();
    }//GEN-LAST:event_btnAddPelicula_btnActionPerformed

    private void btnBuscarPelicula_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPelicula_btnActionPerformed
        // TODO add your handling code here:
        buscarPelicula();
    }//GEN-LAST:event_btnBuscarPelicula_btnActionPerformed

    private void btnAddCliente_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCliente_btnActionPerformed
        // TODO add your handling code here:
        addCliente();
    }//GEN-LAST:event_btnAddCliente_btnActionPerformed

    private void btnBuscarBorrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBorrar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarBorrar_btnActionPerformed

    private void textFecha_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFecha_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFecha_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
        //Añadimos al gestor de Peliculas
        gestorP = new GestorPeliculas();
        gestorC = new GestorClientes();
    }

    //Metodos de botones princiaples
    public void apretarBotonInicio() {
        pnlInicio_pnl.setVisible(true);
        pnlInventario_pnl.setVisible(false);
        pnlClientes_pnl.setVisible(false);
        pnlCaja_pnl.setVisible(false);

        //Marcamos casilla como seleccionada
        btnInicio_pnl.setBackground(new java.awt.Color(130, 38, 104));
        btnInventario_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnClientes_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnCaja_pnl.setBackground(new java.awt.Color(144, 12, 62));
    }

    public void apretarBotonInventario() {
        pnlInicio_pnl.setVisible(false);
        pnlInventario_pnl.setVisible(true);
        pnlClientes_pnl.setVisible(false);
        pnlCaja_pnl.setVisible(false);

        //Marcamos casilla como seleccionada
        btnInicio_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnInventario_pnl.setBackground(new java.awt.Color(130, 38, 104));
        btnClientes_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnCaja_pnl.setBackground(new java.awt.Color(144, 12, 62));
    }

    public void apretarBotonClientes() {
        pnlInicio_pnl.setVisible(false);
        pnlInventario_pnl.setVisible(false);
        pnlClientes_pnl.setVisible(true);
        pnlCaja_pnl.setVisible(false);

        //Marcamos casilla como seleccionada
        btnInicio_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnInventario_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnClientes_pnl.setBackground(new java.awt.Color(130, 38, 104));
        btnCaja_pnl.setBackground(new java.awt.Color(144, 12, 62));
    }

    public void apretarBotonCaja() {
        pnlInicio_pnl.setVisible(false);
        pnlInventario_pnl.setVisible(false);
        pnlClientes_pnl.setVisible(false);
        pnlCaja_pnl.setVisible(true);

        //Marcamos casilla como seleccionada
        btnInicio_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnInventario_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnClientes_pnl.setBackground(new java.awt.Color(144, 12, 62));
        btnCaja_pnl.setBackground(new java.awt.Color(130, 38, 104));
    }

        @SuppressWarnings("empty-statement")
    public void addPelicula() {
        String nombre = " ";
        String genero = " ";
        int estreno = -1;
        int resenha = -1;
        String director = " ";
        String elenco = " ";

        try {
            nombre = JOptionPane.showInputDialog("Introduzca el nombre de la pelicula.");
            if (nombre.isEmpty() || nombre.length() <= 1) {
                throw new IsEmptyException("");
            }

            genero = JOptionPane.showInputDialog("Introduzca el genero de la pelicula.");
            if (genero.isEmpty() || genero.length() <= 3) {
                throw new IsEmptyException("");
            }

            estreno = Integer.parseInt(JOptionPane.showInputDialog("Introduzca el año de estreno de la pelicula."));
            while (estreno < 1000 || estreno > 2025) {
                estreno = Integer.parseInt(JOptionPane.showInputDialog("El año introducido está fuera del rango."));
            }

            resenha = Integer.parseInt(JOptionPane.showInputDialog("Introduzca el rating/reseña de la pelicula.\nDel 1 - 10."));
            while (resenha < 1 || resenha > 10) {
                resenha = Integer.parseInt(JOptionPane.showInputDialog("La reseña está fuera del rango 1-10."));
            }

            director = JOptionPane.showInputDialog("Introduzca el director de la pelicula");
            elenco = JOptionPane.showInputDialog("Introduzca el elenco de la pelicula\nIntroducir actores entre comas.\nEj. Jeniffer Aniston, Matt Leblanc, Tom Hardy");

        } catch (IsEmptyException ex) {
            JOptionPane.showMessageDialog(null, "El valor ingresado no es valido.");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Usted ha decidido cancelar.");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El numero ingresado no es valido.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se.");
        }

        Pelicula nueva = new Pelicula(nombre, genero, resenha, estreno, director, elenco);
        
        if(!(nombre.isEmpty() || nombre.length() <= 1 || genero.isEmpty() || genero.length() <= 3 || estreno < 1000 || estreno > 2025 || resenha < 1 || resenha > 10)){
          gestorP.addPelicula(nueva);  
        }
        
        if (gestorP.existePelicula(nombre)) {
            JOptionPane.showMessageDialog(null, "La Película se agregó correctamente!!");
        } else {
            JOptionPane.showMessageDialog(null, "La pelicula no se puedo añadir, intente nuevamente.");
        }
        
        
        
        
        //Añadimos la pelicula a la lista
        if (gestorP.existePelicula(nombre)) {
        modelPeliculas.insertRow(modelPeliculas.getRowCount(), new Object[]{nombre,genero,estreno,resenha});
        }
    }

    public void eliminarPelicula() {
        String nombre;

        nombre = JOptionPane.showInputDialog("Introduzca el nombre de la pelicula que desea eliminar.");
        if (gestorP.existePelicula(nombre)) {
            gestorP.removePelicula(gestorP.buscarPelicula(nombre));
        } else {
            JOptionPane.showMessageDialog(null, "La pelicula " + nombre + " no existe.");
        }
    }

    public void buscarPelicula() {
        String nombre = JOptionPane.showInputDialog("Introduzca el nombre de la pelicula que desea");
        if (gestorP.existePelicula(nombre)) {
            gestorP.printPelicula(gestorP.buscarPelicula(nombre));
        } else {
            JOptionPane.showMessageDialog(null, "La pelicula " + nombre + " no existe.");
        }
    }
    
    @SuppressWarnings("empty-statement")
    public void addCliente() {
        String nombre = " ";
        String apellido = " ";
        int cedula = -1;
        int deuda = 0;

        try {
            nombre = JOptionPane.showInputDialog("Introduzca el nombre del cliente.");
            if (nombre.isEmpty() || nombre.length() <= 2) {
                throw new IsEmptyException("");
            }
            
            apellido = JOptionPane.showInputDialog("Introduzca el apellido del cliente.");
            if (apellido.isEmpty() || apellido.length() <= 2) {
                throw new IsEmptyException("");
            }
            
            cedula = Integer.parseInt(JOptionPane.showInputDialog("Introduzca el NumCI del cliente."));

        } catch (IsEmptyException ex) {
            JOptionPane.showMessageDialog(null, "El valor ingresado no es valido.");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Usted ha decidido cancelar.");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El numero ingresado no es valido.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se.");
        }

        Cliente nuevo = new Cliente(nombre, apellido, cedula, 0, "");
        
        if(!(nombre.isEmpty() || nombre.length() <= 2 || apellido.isEmpty() || apellido.length() <= 2)){
          gestorC.addCliente(nuevo);  
        }
        
        if (gestorC.existeCliente(cedula)) {
            JOptionPane.showMessageDialog(null, "El cliente se añadio Correctamente!!");
        } else {
            JOptionPane.showMessageDialog(null, "El cliente no se puedo añadir, intente nuevamente.");
        }
        
        
        
        
        //Añadimos la pelicula a la lista
        if (gestorC.existeCliente(cedula)) {
        modelClientes.insertRow(modelClientes.getRowCount(), new Object[]{nombre,apellido,cedula,deuda});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAddCliente_btn;
    private javax.swing.JButton btnAddPelicula_btn;
    private javax.swing.JButton btnBuscarBorrar_btn;
    private javax.swing.JButton btnBuscarPelicula_btn;
    private javax.swing.JPanel btnCaja_pnl;
    private javax.swing.JPanel btnClientes_pnl;
    private javax.swing.JButton btnDevolverPelicula_btn;
    private javax.swing.JPanel btnInicio_pnl;
    private javax.swing.JPanel btnInventario_pnl;
    private javax.swing.JButton btnNuevaOperacionDeAlquiler_btn;
    private javax.swing.JButton btnRefresh_btn;
    private javax.swing.JLabel iconCaja_label;
    private javax.swing.JLabel iconClientes_label;
    private javax.swing.JLabel iconInicio_label;
    private javax.swing.JLabel iconInventario_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblExplicacionPoliticas;
    private javax.swing.JLabel lblExplicacionPoliticas1;
    private javax.swing.JLabel lblExplicacionPoliticas2;
    private javax.swing.JLabel lblExplicacionProgram;
    private javax.swing.JLabel lblExplicacionProgram1;
    private javax.swing.JLabel lblExplicacionProgram2;
    private javax.swing.JLabel lblExplicacionProgram3;
    private javax.swing.JLabel lblExplicacionProgram4;
    private javax.swing.JLabel lblInicio_lbl;
    private javax.swing.JPanel pnlCaja_pnl;
    private javax.swing.JPanel pnlClientes_pnl;
    private javax.swing.JPanel pnlInicio_pnl;
    private javax.swing.JPanel pnlInventario_pnl;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tblaClientes_tble;
    private javax.swing.JTable tblaPeliculas_tble;
    private javax.swing.JLabel textCaja_label;
    private javax.swing.JLabel textClientes_label;
    private javax.swing.JTextField textFecha_field;
    private javax.swing.JLabel textFecha_lbl;
    private javax.swing.JLabel textInicio_label;
    private javax.swing.JLabel textInventario_label;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
    private static GestorPeliculas gestorP;
    private static GestorClientes gestorC;
}
